andgineer/TRegExpr

.gitignore, examples/TRegExprRoutines/TRegExprRoutinesMain.dfm, examples/TRegExprRoutines/TRegExprRoutinesMain.pas, examples/Text2HTML/Text2HTML.dpr
Good Morning!
I've find your repo and i like it! It's helps me a lot. So, i just fix some little bugs to fulfill another user's experience and testings! 
So long and Keep Coding!
=> Some testings troubles!

src/RegExpr.pas
D7 don't support "inline" keyword
=> $Ifdef for inline keyword for support Delphi 7

docs/faq.rst
text: How to parse sources like HTML with help of TRegExpr
=> add question mark at "How to... of TRegExpr"

History.txt, ToDo.txt, src/RegExpr.pas
=> change type of fInputString/fExpression from PChar to string, clearer code

History.txt, src/RegExpr.pas, test/tcregexp.pas
http://www.qnx.com/developers/docs/6.6.0_anm11_wf10/com.qnx.doc.dinkum/topic/cpp11/lib_regex.html#control%20escape%20sequence
=> support control escape sequences \cA .. \cZ

src/RegExpr.pas
=> rename generic const names (OPEN, STAR, CLOSE, LOOP...) - add OP_ prefix

src/RegExpr.pas
=> unify char-test funcs; convert methods->normal funcs; fix wrong renames in comments

test/tests.pas
=> Add tests for specific valid regex set

test/tests.pas
=> Revert "Add tests for specific valid regex set"

test/tests.pas
Something went wrong with #156 ...
=> Fix compilation of tests

test/tests.pas
=> Fix test 44

src/regexpr.pas, test/tests.pas
=> optimize \b \B handler; added test for \B

src/regexpr.pas
Patch for issue 241 as requested.
=> * Fix compilation for D2009> when no FastUniCodeData is defined

History.txt, docs/regular_expressions.rst, src/regexpr.pas, test/tests.pas, test_dlg/unit1.pas
See #297
This is based on #300 as some changes affect nearby lines and lead to conflicts if individually applied.
Once #300 is merged, only one commit should remain to be merged.
=> Implement \G #297

src/regexpr.pas, test/tests.pas
Some changes for PR #312 / Part of Issue #314
=> Follow up to PR #312  / Issue #314

src/regexpr.pas
=> Clear last error, before execution.

docs/regular_expressions.rst
=> Docs for recent changes

History.txt, docs/regular_expressions.rst, src/regexpr.pas, test/tests.pas
=> support \R. fix https://github.com/andgineer/TRegExpr/issues/286

History.txt, src/regexpr.pas, test/tests.pas, test_benchmark/test.lpr
=> Fix issue 339

src/regexpr.pas
I wonder if the code in the IFDEF should use `Error`, or if instead of the IFDEF, it should be an `assert`?
I overlooked one instance of `reeBadOpcodeInCharClass` => because at the end of a if/else waterfall it adds no extra time.
I disabled WITH_REGEX_ASSERT in Delphi, as I don't know the "IFOPT" alternative.
Benchmarks
```
Running 8 repeats for each benchmark. Use -c <n> to change
Before   | After     | Match count
==============================================================================
regexpr.pas:
/Twain/ :          29 ms |     29 ms |       2388
/(?i)Twain/ :          54 ms |     54 ms |       2657
/[a-z]shing/ :         230 ms |    230 ms |       1877
/Huck[a-zA-Z]+|Saw[a-zA-Z]+/ :          33 ms |     31 ms |        396
/./ :         445 ms |    419 ms |   18905427
/(.)/ : …
```
=> speed up / Use assert to check for corrupt mem

src/regexpr.pas
If all chars in a group are case-unspecific e.g. `[0123,!]` then use non CI variant
Saves doing an uppercase during exec.
=> If OpAny/But are in CI mode but non of the chars has case 

src/regexpr.pas
Limit look-behind attempt to the now known max-length
Some look behind will be a lot faster.
=> Improved IsFixedLength to get min and max. 

src/regexpr.pas, test/tests.pas
no longer used / faster without
=> Cleanup regcurrentgroup

src/regexpr.pas, test/tests.pas
There was a bug in lookaround patterns. See commit description.
=> Fix look around

src/regexpr.pas
2 small fixes / see commit description
=> Fix overflow in IsPartFixedLength / remove incorrect assert.

docs/regular_expressions.rst
=> Docs for \K

src/regexpr.pas, test/tests.pas
Slight improvement in speed. Not represented in the benchmark. But in an app of mine it gives about 2% improvement.
=> More guarded branch

src/regexpr.pas, test_dlg/unit1.lfm, test_dlg/unit1.pas
Improve the output of dump.
- look around will get indented
- Each section of a branch will now be indented.
=> Add more indent to Dump()

src/regexpr.pas, test/tests.pas
Sorry, mistake in the last commit
=> Fix GBranch with OP_PLUS

src/regexpr.pas
Since loops use branches (in some cases) let they benefit from the OP_GBRANCH
=> Use gbranch in *+ and ?

History.txt, src/regexpr.pas, test/tests.pas
One tiny optimization, some tests, and fix for #376
=> fix #376 / small optimizations

History.txt, src/regexpr.pas, test/tests.pas
See Issue #388
Also improved FirstCharSet
=> Allow OP_ANY_ML in simple loops (OP_STAR). Issue #388
